### ISSUE TITLE
Problems with HTTP client

### ISSUE THREAD

**Issue by Nutomic** [marinintim/webmention#1]
Hi, I came across your client while trying to implement webmentions for [Lemmy](https://join-lemmy.org/). Integrating it looked pretty straightforward, but I ran into a few problems with the HTTP client.

First, the libcurl dependency used by surf doesnt seem to work in our Alpine Docker container, even after running `apk add libcurl` it crashes with `error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory`. I managed to work around that with the solution mentioned [here](https://github.com/http-rs/surf/issues/112#issuecomment-571249953). 

Then I got another error, this time related to SSL: `error sending request for url (https://webmention.rocks/test/1): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (unable to get local issuer certificate)`.

I dont know if you picked surf as your HTTP client for a specific reason, but for us it has the additional disadvantage that we would be pulling in a second HTTP client, besides [reqwest](https://crates.io/crates/reqwest) which we are using now. So from my perspective it would be preferable to replace surf with reqwest in this crate (or allow choosing between them via feature flag). In my experience reqwest also works more smootly, I never saw errors like those above while using it.

[Issue in our repo](https://github.com/LemmyNet/lemmy/issues/1395)

**Comment by timmarinin** [comment]
Hi, @Nutomic! I'll try to reproduce it.

**Comment by timmarinin** [comment]
@Nutomic: I've published 0.1.3 which adds feature `hyper` to force surf to use hyper (which reqwest is based on, afaik); could you try it out?

**Comment by Nutomic** [comment]
Thanks for the update, however I'm still getting the "error while loading libcurl". I believe this is because surf has the curl feature enabled by default, so you need to use `default-features = false`. [Here is my PR](https://github.com/LemmyNet/lemmy/pull/1671), if you want to try it yourself, you can clone the repo and run `docker/dev/docker_update.sh`.

**Comment by timmarinin** [comment]
@Nutomic: for some reason I do not get this error on macOS while trying to build your PR via `docker/dev/docker_update.sh`, I get another bunch of errors, which also reproduce on `main` branch.

After a little digging and doing `git rebase -i f4c7c2bf28fa0ea0ee80d4e0b8a1340c9576e0f2` of `support-webmentions` branch, I was able to build a docker image without errors.

**Comment by Nutomic** [comment]
Sorry my bad, the problem only happens with `docker_update_volume_mount.sh`.

**Comment by timmarinin** [comment]
@Nutomic: I've published 0.2.0, so can you try `webmention = "0.2.0"`? It should not include curl now at all (and it disappears from the cargo lock)

**Comment by Nutomic** [comment]
Great, thank you! Unfortunately there is another problem when sending the webmention (via http://localhost:1235/create_post):

```
lemmy_1     | thread 'main' panicked at 'not currently running on a Tokio 0.2.x runtime.', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/handle.rs:118:28
lemmy_1     | stack backtrace:
lemmy_1     |    0: rust_begin_unwind
lemmy_1     |              at ./rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
lemmy_1     |    1: core::panicking::panic_fmt
lemmy_1     |              at ./rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
lemmy_1     |    2: core::option::expect_failed
lemmy_1     |              at ./rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1292:5
lemmy_1     |    3: core::option::Option<T>::expect
lemmy_1     |    4: tokio::runtime::handle::Handle::current
lemmy_1     |    5: tokio::runtime::blocking::pool::spawn_blocking
lemmy_1     |    6: tokio::task::blocking::spawn_blocking
lemmy_1     |    7: <hyper::client::connect::dns::GaiResolver as tower_service::Service<hyper::client::connect::dns::Name>>::call
lemmy_1     |    8: <S as hyper::client::connect::dns::sealed::Resolve>::resolve
lemmy_1     |    9: hyper::client::connect::dns::resolve::{{closure}}
lemmy_1     |   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
lemmy_1     |   11: hyper::client::connect::http::HttpConnector<R>::call_async::{{closure}}
lemmy_1     |   12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
lemmy_1     |   13: <hyper::client::connect::http::HttpConnector<R> as tower_service::Service<http::uri::Uri>>::call::{{closure}}
lemmy_1     |   14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
lemmy_1     |   15: <core::pin::Pin<P> as core::future::future::Future>::poll
lemmy_1     |   16: <hyper::client::connect::http::HttpConnecting<R> as core::future::future::Future>::poll
lemmy_1     |   17: <hyper_tls::client::HttpsConnector<T> as tower_service::Service<http::uri::Uri>>::call::{{closure}}
lemmy_1     |   18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
lemmy_1     |   19: <core::pin::Pin<P> as core::future::future::Future>::poll
lemmy_1     |   20: <hyper_tls::client::HttpsConnecting<T> as core::future::future::Future>::poll
lemmy_1     |   21: <hyper::service::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
lemmy_1     |   22: <F as futures_core::future::TryFuture>::try_poll
lemmy_1     |   23: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
lemmy_1     |   24: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
lemmy_1     |   25: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
lemmy_1     |   26: <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll
lemmy_1     |   27: <F as futures_core::future::TryFuture>::try_poll
lemmy_1     |   28: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
lemmy_1     |   29: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
lemmy_1     |   30: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
lemmy_1     |   31: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
lemmy_1     |   32: <F as futures_core::future::TryFuture>::try_poll
lemmy_1     |   33: <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll
lemmy_1     |   34: <futures_util::future::try_future::TryFlatten<Fut1,Fut2> as core::future::future::Future>::poll
lemmy_1     |   35: <futures_util::future::try_future::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll
lemmy_1     |   36: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
lemmy_1     |   37: <hyper::common::lazy::Lazy<F,R> as core::future::future::Future>::poll
lemmy_1     |   38: futures_util::future::future::FutureExt::poll_unpin
lemmy_1     |   39: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
lemmy_1     |   40: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
lemmy_1     |   41: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
lemmy_1     |   42: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
lemmy_1     |   43: <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
lemmy_1     |   44: <F as futures_core::future::TryFuture>::try_poll
lemmy_1     |   45: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
lemmy_1     |   46: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
lemmy_1     |   47: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
lemmy_1     |   48: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
lemmy_1     |   49: <F as futures_core::future::TryFuture>::try_poll
lemmy_1     |   50: <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll
lemmy_1     |   51: <futures_util::future::try_future::TryFlatten<Fut1,Fut2> as core::future::future::Future>::poll
lemmy_1     |   52: <futures_util::future::try_future::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll
lemmy_1     |   53: hyper::client::Client<C,B>::retryably_send_request::{{closure}}
lemmy_1     |   54: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
lemmy_1     |   55: <core::pin::Pin<P> as core::future::future::Future>::poll
lemmy_1     |   56: <hyper::client::ResponseFuture as core::future::future::Future>::poll
lemmy_1     |   57: <http_client::hyper::HyperClient as http_client::HttpClient>::send::{{closure}}
lemmy_1     |   58: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
lemmy_1     |   59: <core::pin::Pin<P> as core::future::future::Future>::poll
lemmy_1     |   60: surf::client::Client::send::{{closure}}::{{closure}}::{{closure}}
lemmy_1     |   61: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
lemmy_1     |   62: <core::pin::Pin<P> as core::future::future::Future>::poll
lemmy_1     |   63: <surf::middleware::logger::native::Logger as surf::middleware::Middleware>::handle::{{closure}}
lemmy_1     |   64: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
lemmy_1     |   65: <core::pin::Pin<P> as core::future::future::Future>::poll
lemmy_1     |   66: surf::client::Client::send::{{closure}}
lemmy_1     |   67: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
lemmy_1     |   68: webmention::http_client::get::{{closure}}
lemmy_1     |   69: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
lemmy_1     |   70: webmention::webmention::Webmention::check::{{closure}}
lemmy_1     |   71: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
lemmy_1     |   72: webmention::webmention::Webmention::send::{{closure}}
lemmy_1     |   73: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
lemmy_1     |   74: lemmy_api_crud::post::create::<impl lemmy_api_crud::PerformCrud for lemmy_api_common::post::CreatePost>::perform::{{closure}}
lemmy_1     |   75: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
lemmy_1     |   76: <core::pin::Pin<P> as core::future::future::Future>::poll
lemmy_1     |   77: lemmy_api_crud::do_websocket_operation::{{closure}}
lemmy_1     |   78: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
lemmy_1     |   79: lemmy_api_crud::match_websocket_operation_crud::{{closure}}
lemmy_1     |   80: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
lemmy_1     |   81: <core::pin::Pin<P> as core::future::future::Future>::poll
lemmy_1     |   82: lemmy_utils::rate_limit::RateLimited::wrap::{{closure}}
lemmy_1     |   83: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
lemmy_1     |   84: lemmy_websocket::chat_server::ChatServer::parse_json_message::{{closure}}
lemmy_1     |   85: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
lemmy_1     |   86: lemmy_websocket::handlers::<impl actix::handler::Handler<lemmy_websocket::messages::StandardMessage> for lemmy_websocket::chat_server::ChatServer>::handle::{{closure}}
lemmy_1     |   87: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
lemmy_1     |   88: <core::pin::Pin<P> as core::future::future::Future>::poll
lemmy_1     |   89: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future+Output = <M as actix::handler::Message>::Result>> as actix::handler::MessageResponse<A,M>>::handle::{{closure}}
lemmy_1     |   90: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
lemmy_1     |   91: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
lemmy_1     |   92: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
lemmy_1     | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

It seems like we are on tokio 1.8.0, so you are using an outdated version?

**Comment by timmarinin** [comment]
@Nutomic ok, I’ve published 0.3.0 which switches to reqwest with the same version as lemmy api_crud uses, which should solve the issue (if reqwest is capable of sending tls requests in such configuration).

Regarding your pull request, the source for webmention should be the permalink of the post rather than the homepage

**Comment by Nutomic** [comment]
Thanks, now there is no more error, but webmention.send() simply returns `Ok(false)`, and I have no idea what it means. I suggest that you change the return type of send() to `Result<(), WebmentionError>`, and include an actual error message if the webmention cant be sent for any reason.

Btw there is no need that you keep making new releases at this point, I can just pull from a branch in your git repo until my pr is ready to merge.

**Comment by timmarinin** [comment]
@Nutomic: I think that the problem currently is with checking the validity of the webmention before sending it, which could happen if the HTML doesn't contain the target URL directly. Other errors should bubble up as errors.

You can avoid checking by calling `.set_checked(true)` before sending.

In the branch `feature/response` I've added an enum to distinguish between "NotValid" / "Accepted" / "NotAccepted"

**Comment by Nutomic** [comment]
The `feature/response` is very useful, it tells me `Error during message handling generic request failed for URL <https://lemmy-alpha/>`, so thats just because Lemmy runs on a different port for local testing, and that port isnt included in the source url. That wont happen in production as it has to run on default port, so `set_checked` is a perfect solution. 

The ssl error i mentioned before was because ssl is broken in that test docker image, sorry if you wasted any time investigating that. If i run it locally without docker, it connects fine.

Now i'm getting `Error during message handling webmention was not accepted by endpoint <https://webmention.rocks/test/1/webmention>`, so the server is receiving it. I suspect thats because i'm sending the webmention from localhost, so the server cant verify the source url. Which means we have to test it from an actual server.

Another problem is that Webmention.send() returns an error if no webmention endpoint is discovered. I would like to ignore that error (and similar ones), but it seems impossible currently as `WebmentionError` doesnt implement Eq. I guess the vast majority of urls dont support webmentions, so i dont want to spam the logs with that, but it seems wrong to ignore errors completely.

Btw, for convenience it would be nice if you could add a more ergonomic way to initialize the Webmention struct, something like `Webmention::new(source_url, target_url)`.

**Comment by timmarinin** [comment]
@Nutomic: you're making a good case, I've added it as a variant of WebmentionAcceptance: NoTargetEndpoint in `feature/response`, as well as `Webmention::new` from two AsRef<str> (see test https://github.com/marinintim/webmention/blob/feature/response/src/webmention.rs#L129)

**Comment by Nutomic** [comment]
Finally got back to this. About the constructor, I noticed that I can simply use `Webmention::from((Url, Url))`. That works for me, your new constructor isnt that useful for me because I already have Urls, so no need to convert back and forth. I would just provide a single way to construct Webmention, namely `Webmention::new(Url, Url)`. I dont think there is any need for a From implementation or a constructor that takes &str. But of course thats your decision.

I finally tested it on a server, and it [seems to work fine](https://webmention.rocks/test/1). I assume the "comment text not found" etc is because webmention.rocks cant parse the HTML from Lemmy? Or is there anything else I need to do?

![Screenshot_20210917_152408](https://user-images.githubusercontent.com/1044450/133789809-7376cd6d-48b3-4866-a302-8ae5197c6f42.jpg)

If it looks correct to you, then we can merge this into Lemmy after you make a new release with the `feature/response` branch changes.

**Comment by timmarinin** [comment]
@Nutomic: yeah, webmention.rocks tries to parse microformats from the `source` (in the case of Lemmy, as far as I understand it, the most appropriate is [bookmark](https://indieweb.org/bookmark)). I'll cut a release later today then, great to hear it :)

**Comment by Nutomic** [comment]
New release is out, so I consider this issue solved. Thanks a lot :)
